### ISSUE TITLE
Avoid outputting empty @media blocks

### ISSUE THREAD

**Issue by fetimo** [jameslnewell/styled-components-breakpoint#13]
Hi,

How easy would it be to avoid outputting empty `@media` blocks? A colleague and I had a go at it but couldn't work out how to determine if the block would be empty before handing off to the `css` constructor.

**Comment by jameslnewell** [comment]
👋 I think it'd just be a matter of checking whether the strings were empty [here](https://github.com/jameslnewell/styled-components-breakpoint/blob/master/src/core.js#L50)

**Comment by JamesBliss** [comment]
Hi, 

I'm the colleague. Our issue is that many of the breakpoints have conditionals such as:

`${ props => (props.phoneMargin ? `margin: ${ props.phoneMargin }` : null) }`

Obviously we do not want a media block to render if null is output but we cannot figure out if that can be done or if we just need to wrap the breakpoint in the conditional which isn't ideal?

**Comment by jameslnewell** [comment]
Ah it looks like we'd need to evaluate `interpolations` with `props` (e.g. `${props => css(strings, ...interpolations.map(interpolation => interpolation(props))}`), and then check whether all the strings and interpolated values were empty... 

Feels rather complicated. Is there a reason you are concerned about the empty media blocks?
