### ISSUE TITLE
Usage in JSX

### ISSUE THREAD

**Issue by slorenzo** [jameslnewell/styled-components-breakpoint#14]
Hello!
Is there a way to use this in JSX?
For instance, I want to change the aspect ratio of the [cards](http://react-toolbox.io/#/components/card).

```
<CardMedia
  aspectRatio={breakpoint('tablet') ? 'square' : 'wide'}
  image={object.image}
/>
```

If not, It could be a really good improvement.
Thanks!

**Comment by jameslnewell** [comment]
👋The library doesn't support this functionality at the moment.

I can see how the feature would be really helpful. It'd need to call `matchMedia` which feels a little out of scope of this library and styled-components other than the fact that they both use the same breakpoints. I think I'd probably lean for another package that could be configured from the exact same breakpoints e.g. 

```js
import create from 'breakpoints';

const breakpoints = create({ // same values as passed to styled-components-breakpoint
  sm: 100,
  md: 200,
  lg: 300
});

<CardMedia aspectRatio={breakpoints.is('sm') ? 'square' : 'wide'}/>

```
This would be very similar to [breakpoints-js](https://www.npmjs.com/package/breakpoints-js).

What do you think?

**Comment by slorenzo** [comment]
Yes, there are many occasions when it would really helpful.

I will look at the different alternatives to solve this issue, [breackpoint-js](https://www.npmjs.com/package/breakpoints-js) seems at first a good solution. 

Thanks for your suggestion! ;)

**Comment by jameslnewell** [comment]
👍 feel free to propose a better API after playing around with alternatives!
