### ISSUE TITLE
Peer dependency for styled-components should include v4 as well.

### ISSUE THREAD

**Issue by callmeberzerker** [jameslnewell/styled-components-breakpoint#17]

**Comment by daviddelusenet** [comment]
+1

Is there any progress on this?

**Comment by jameslnewell** [comment]
Not at the moment. Please create a PR bumping the `version` and `peerDependency` and I'll merge + publish.

**Comment by daviddelusenet** [comment]
@jameslnewell I fixed this on a local branch but when trying to push I get the following error:

```
ERROR: Permission to jameslnewell/styled-components-breakpoint.git denied to daviddelusenet.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by callmeberzerker** [comment]
@daviddelusenet you need to create Pull Request -> not to try to push directly to this repo.

**Comment by daviddelusenet** [comment]
@SpearThruster I cloned this repo locally, made a new branch called `styled-components-peer-dependency-update` and then followed the [following instructions](https://services.github.com/on-demand/github-cli/open-pull-request-github).

After executing ` git push -u origin styled-components-peer-dependency-update` (so the first step) I get the error mentioned above.

Am I doing something wrong?

**Comment by callmeberzerker** [comment]
@daviddelusenet did you fork this repo? and then you need to clone your own repo?

**Comment by daviddelusenet** [comment]
This issue is fixed in https://github.com/jameslnewell/styled-components-breakpoint/pull/18

**Comment by jameslnewell** [comment]
Thanks!
