### ISSUE TITLE
Question. Is there a way to do media queries in between?

### ISSUE THREAD

**Issue by marhalpert** [jameslnewell/styled-components-breakpoint#6]
Hi @jameslnewell,

I was just wondering if there was a way to do something like this:

```css
@media (min-width: 46.0625em) and (max-width: 64.0625em) { ... }
```

Thanks!

**Comment by jameslnewell** [comment]
Hi @marhalpert. Thanks for getting in touch! There isn't a way to do this at the moment. I have been meaning to get round to implementing the rest of the mixins from my sass library ([sass-breakpoints](https://www.npmjs.com/package/sass-breakpoints#api)) but haven't found the time or the need yet. 

I'd be happy to consider a PR.

**Comment by jameslnewell** [comment]
@marhalpert what do you mean by between? inclusive (or exclusive) at both (or just one) ends?

**Comment by jameslnewell** [comment]
I've added `breakpoint(gte, lt)` in `v2`

**Comment by marhalpert** [comment]
👍
